name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn
      run: yarn --network-concurrency 1
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
      env:
        CI: true
    - name: build
      run: yarn build
